import {
  AppstoreOutlined,
  FileSyncOutlined,
  FileDoneOutlined,
  StopOutlined,
  WechatOutlined,
  UserSwitchOutlined,
  ShoppingCartOutlined,
  BarChartOutlined,
  TeamOutlined,
  SettingOutlined,
  ExportOutlined,
  ImportOutlined,
  WarningOutlined,
  DatabaseOutlined,
  DollarOutlined,
  FileSearchOutlined,
  TruckOutlined,
  UnorderedListOutlined,
  RiseOutlined,
  FallOutlined,
  AuditOutlined,
} from "@ant-design/icons";

const storeMenu = [
  { key: "store-1", label: "Dashboard", icon: <BarChartOutlined />, path: "/shared/store/dashboard" },
  { key: "store-2", label: "Stock Items", icon: <AppstoreOutlined />, path: "/shared/store/stock/items" },
  { key: "store-3", label: "Pending Requests", icon: <FileSyncOutlined />, path: "/shared/store/pending-requests" },
  { key: "store-4", label: "Approved Requests", icon: <FileDoneOutlined />, path: "/shared/store/approved-requests" },
  { key: "store-5", label: "Expired Items", icon: <StopOutlined />, path: "/shared/store/expired-items" },
  { key: "store-6", label: "Issued Items", icon: <FileDoneOutlined />, path: "/shared/store/issued-items" },
  { key: "store-7", label: "Low Stock Alert", icon: <WarningOutlined />, path: "/shared/store/low-stock" },
  { key: "store-8", label: "Suppliers", icon: <TeamOutlined />, path: "/shared/store/suppliers" },
  { key: "store-9", label: "Purchase Orders", icon: <ShoppingCartOutlined />, path: "/shared/store/purchase-orders" },
  { key: "store-10", label: "Inventory In", icon: <ImportOutlined />, path: "/shared/store/inventory-in" },
  { key: "store-11", label: "Inventory Out", icon: <ExportOutlined />, path: "/shared/store/inventory-out" },
  { key: "store-12", label: "Stock Transfer", icon: <DatabaseOutlined />, path: "/shared/store/stock-transfer" },
  { key: "store-23", label: "Stock Adjustment", icon: <RiseOutlined />, path: "/shared/store/stock-adjustment" },
  // ERP Additional Features
  { key: "store-14", label: "Stock Valuation", icon: <DollarOutlined />, path: "/shared/store/stock-valuation" },
  { key: "store-15", label: "Reorder Points", icon: <WarningOutlined />, path: "/shared/store/reorder-points" },
  { key: "store-16", label: "Stock Reports", icon: <FileSearchOutlined />, path: "/shared/store/reports" },
  { key: "store-17", label: "Stock Movement", icon: <UnorderedListOutlined />, path: "/shared/store/stock-movement" },
  { key: "store-18", label: "Purchase Returns", icon: <FallOutlined />, path: "/shared/store/purchase-returns" },
  { key: "store-19", label: "Supplier Payments", icon: <DollarOutlined />, path: "/shared/store/supplier-payments" },
  { key: "store-20", label: "Stock Audit", icon: <AuditOutlined />, path: "/shared/store/stock-audit" },
  { key: "store-21", label: "Department Inventory", icon: <DatabaseOutlined />, path: "/shared/store/department-inventory" },
  { key: "store-22", label: "Asset Management", icon: <AppstoreOutlined />, path: "/shared/store/assets" },
  { key: "consult-4", label: "Message", icon: <WechatOutlined />, path: "/shared/chat" },
  { key: "record-9", label: "Attendance", icon: <UserSwitchOutlined />, path: "/shared/attendance" },
  { key: "store-13", label: "Settings", icon: <SettingOutlined />, path: "/shared/store/settings" },
];

export default storeMenu;
