import React from 'react';
import { Modal, Descriptions, Tag, Divider, Alert } from 'antd';
import moment from 'moment';

const ExportBatchModal = ({ visible, batch, onClose }) => {
  if (!batch) return null;

  const getStatusDetails = (status) => {
    const statusConfig = {
      Pending: {
        color: 'orange',
        message: 'This batch is currently pending processing.',
        description: 'The export batch has been created and is waiting to be processed.'
      },
      Completed: {
        color: 'green',
        message: 'This batch has been successfully processed.',
        description: 'The export batch has been completed and is ready for download.'
      },
      Failed: {
        color: 'red',
        message: 'This batch processing has failed.',
        description: 'There was an error processing this export batch.'
      },
      Processing: {
        color: 'blue',
        message: 'This batch is currently being processed.',
        description: 'The export batch is being generated. Please wait...'
      }
    };
    return statusConfig[status] || statusConfig.Pending;
  };

  const statusDetails = getStatusDetails(batch.export_status);

  return (
    <Modal
      title="Export Batch Details"
      open={visible}
      onCancel={onClose}
      footer={null}
      width={700}
      centered
    >
      <Alert
        message={statusDetails.message}
        description={statusDetails.description}
        type={
          batch.export_status === 'Completed' ? 'success' :
          batch.export_status === 'Failed' ? 'error' :
          batch.export_status === 'Processing' ? 'info' : 'warning'
        }
        showIcon
        className="mb-4"
      />

      <Descriptions column={1} bordered size="small">
        <Descriptions.Item label="Batch Number">
          <span className="font-mono">{batch.batch_number}</span>
        </Descriptions.Item>
        
        <Descriptions.Item label="Institution">
          {batch.institution || 'N/A'}
        </Descriptions.Item>
        
        <Descriptions.Item label="Generated Date">
          <div className="flex flex-col">
            <span>{moment(batch.createdAt).format('MMMM DD, YYYY')}</span>
            <span className="text-gray-500 text-sm">
              {moment(batch.createdAt).format('hh:mm A')}
            </span>
            <span className="text-gray-400 text-xs">
              ({moment(batch.createdAt).fromNow()})
            </span>
          </div>
        </Descriptions.Item>
        
        <Descriptions.Item label="Generated By">
          {batch.generated_by || 'System'}
        </Descriptions.Item>
        
        <Descriptions.Item label="File Name">
          <span className="font-mono text-sm">{batch.file_name}</span>
        </Descriptions.Item>
        
        <Descriptions.Item label="File Path">
          <span className="font-mono text-xs text-gray-600 break-all">
            {batch.file_path}
          </span>
        </Descriptions.Item>
        
        <Descriptions.Item label="Total Claims">
          <Tag color="blue">{batch.total_claims}</Tag>
        </Descriptions.Item>
        
        <Descriptions.Item label="Total Amount">
          <span className="font-semibold text-lg">
            ${parseFloat(batch.total_amount || 0).toLocaleString()}
          </span>
        </Descriptions.Item>
        
        <Descriptions.Item label="Status">
          <Tag color={statusDetails.color} className="capitalize">
            {batch.export_status}
          </Tag>
        </Descriptions.Item>
      </Descriptions>

      {batch.export_status === 'Pending' && (
        <>
          <Divider />
          <div className="bg-yellow-50 border border-yellow-200 rounded p-3">
            <h4 className="font-semibold text-yellow-800 mb-2">
              Pending Batch Information
            </h4>
            <p className="text-yellow-700 text-sm">
              This batch is queued for processing. It will be processed shortly. 
              You can check back later to see the updated status and download the file.
            </p>
          </div>
        </>
      )}
    </Modal>
  );
};

export default ExportBatchModal;