import React, { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Table, Card, Tag, Button, Space, Spin, Empty } from 'antd';
import { EyeOutlined, CodeOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import moment from 'moment';
import { listExportBatches } from '../../../../redux/slice/claimSlice';
import ExportBatchModal from './components/ExportBatchModal';

const ClaimsExportHistory = () => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const { exportBatches, loading } = useSelector((state) => state.claims);
  const [selectedBatch, setSelectedBatch] = useState(null);
  const [modalVisible, setModalVisible] = useState(false);

  React.useEffect(() => {
    dispatch(listExportBatches());
  }, [dispatch]);

  const handleViewBatch = (batch) => {
    setSelectedBatch(batch);
    setModalVisible(true);
  };

  const handleViewXml = (batch) => {
    console.log('Viewing XML for batch:', batch);
    // Navigate to XML viewer page with batch data
    navigate('/shared/claims/history/xml-viewer', { state: { batch } });
  };

  const handleCloseModal = () => {
    setModalVisible(false);
    setSelectedBatch(null);
  };

  const getStatusColor = (status) => {
    const statusColors = {
      Pending: 'orange',
      Completed: 'green',
      Failed: 'red',
      Processing: 'blue',
    };
    return statusColors[status] || 'default';
  };

  const columns = [
    {
      title: 'Batch Number',
      dataIndex: 'batch_number',
      key: 'batch_number',
      render: (text) => (
        <span className="font-mono text-sm text-gray-800">{text}</span>
      ),
    },
    {
      title: 'Institution',
      dataIndex: 'institution',
      key: 'institution',
      render: (text) => (
        <span className="text-gray-700">{text || 'N/A'}</span>
      ),
    },
    {
      title: 'Generated Date',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (date) => (
        <div className="flex flex-col">
          <span className="text-sm font-medium text-gray-900">
            {moment(date).format('MMM DD, YYYY')}
          </span>
          <span className="text-xs text-gray-500">
            {moment(date).format('hh:mm A')}
          </span>
        </div>
      ),
      sorter: (a, b) => moment(a.createdAt) - moment(b.createdAt),
    },
    {
      title: 'Generated By',
      dataIndex: 'generated_by',
      key: 'generated_by',
      render: (text) => (
        <span className="text-gray-700">{text || 'System'}</span>
      ),
    },
    {
      title: 'Total Claims',
      dataIndex: 'total_claims',
      key: 'total_claims',
      align: 'center',
      render: (count) => (
        <span className="px-2 py-1 bg-blue-100 text-blue-800 rounded-full text-sm font-medium">
          {count}
        </span>
      ),
    },
    {
      title: 'Total Amount',
      dataIndex: 'total_amount',
      key: 'total_amount',
      render: (amount) => (
        <span className="font-medium text-gray-900">
          ${parseFloat(amount || 0).toLocaleString()}
        </span>
      ),
    },
    {
      title: 'Status',
      dataIndex: 'export_status',
      key: 'export_status',
      render: (status) => (
        <Tag color={getStatusColor(status)} className="capitalize">
          {status}
        </Tag>
      ),
    },
    {
      title: 'Actions',
      key: 'actions',
      render: (_, record) => (
        <Space>
          <Button
            type="link"
            icon={<EyeOutlined />}
            onClick={() => handleViewBatch(record)}
            className="text-blue-600 hover:text-blue-800"
          >
            Details
          </Button>
          <Button
            type="link"
            icon={<CodeOutlined />}
            onClick={() => handleViewXml(record)}
            // disabled={record.export_status !== 'Completed'}
            className="text-green-600 hover:text-green-800"
          >
            View XML
          </Button>
        </Space>
      ),
    },
  ];

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <Spin size="large" tip="Loading export history..." />
      </div>
    );
  }

  return (
    <div className="p-6">
      <Card
        title="Claims Export History"
        className="shadow-sm"
        extra={
          <Button 
            type="primary" 
            onClick={() => dispatch(listExportBatches())}
            loading={loading}
          >
            Refresh
          </Button>
        }
      >
        {exportBatches?.length > 0 ? (
          <Table
            columns={columns}
            dataSource={exportBatches}
            rowKey="id"
            pagination={{
              pageSize: 10,
              showSizeChanger: true,
              showQuickJumper: true,
              showTotal: (total, range) =>
                `${range[0]}-${range[1]} of ${total} items`,
            }}
            scroll={{ x: 1000 }}
          />
        ) : (
          <Empty
            description="No export batches found"
            image={Empty.PRESENTED_IMAGE_SIMPLE}
          />
        )}
      </Card>

      <ExportBatchModal
        visible={modalVisible}
        batch={selectedBatch}
        onClose={handleCloseModal}
      />
    </div>
  );
};

export default ClaimsExportHistory;